[versions]
android-plugins = "7.0.0"
kotest = "5.8.0"
kotlin = "1.9.22"

[libraries]
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-framework-datatest = { module = "io.kotest:kotest-framework-datatest", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
kotlin-test-common = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "kotlin" }
kotlin-test-annotations-common = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "kotlin" }

[bundles]
kotest-common = [
    "kotest-assertions-core",
    "kotest-framework-engine",
    "kotest-framework-datatest",
]
kotlin-testing-common = [
    "kotlin-test-common",
    "kotlin-test-annotations-common",
]

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotest-multiplatform = { id = "io.kotest.multiplatform", version.ref = "kotest" }
dokka = "org.jetbrains.dokka:1.9.10"
gitSemVer = "org.danilopianini.git-sensitive-semantic-versioning-gradle-plugin:3.1.1"
kotlin-qa = "org.danilopianini.gradle-kotlin-qa:0.60.0"
multiJvmTesting = "org.danilopianini.multi-jvm-test-plugin:0.5.8"
npm-publish = "dev.petuska.npm.publish:3.4.2"
publishOnCentral = "org.danilopianini.publish-on-central:5.0.23"
taskTree = "com.dorongold.task-tree:2.1.1"
